# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# 每日早9点到晚8点每2小时运行一次

name: 中青看看赚

on:
  workflow_dispatch:
  schedule:
     - cron: '55 14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_START: ${{ secrets.YOUTH_START }}
      YOUTH_END: ${{ secrets.YOUTH_END }}
      YOUTH_START2: ${{ secrets.YOUTH_START2 }}
      YOUTH_END2: ${{ secrets.YOUTH_END2 }}
      YOUTH_START3: ${{ secrets.YOUTH_START3 }}
      YOUTH_END3: ${{ secrets.YOUTH_END3 }}
      TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看看赚任务一】'
        if: env.YOUTH_START
        run: |
          node Task/youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START }}
          YOUTH_ATIME: ${{ secrets.YOUTH_END }}

      - name: '运行 【中青看看赚任务二】'
        if: env.YOUTH_START2
        run: |
          node Task/youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START2 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_END2 }}
          
      - name: '运行 【中青看看赚任务三】'
        if: env.YOUTH_START3
        run: |
          node Task/youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START3 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_END3 }}
          
      - name: '运行 【中青看看赚任务四】'
        if: env.YOUTH_START4
        run: |
          node Task/youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START4 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_END4 }}
